# Generated by Django 4.2.2 on 2023-06-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
